# Contains all the configuration of the services that make app the application

#Version of docker compose
version: "3"

#Service for python django framework
services:
  app:
    build:
      # . declares the current configuration
      context: .
    ports:
      - "8000:8000"
    # volumes allows us to automatically update any change to the docker image  
    volumes:
      - ./app:/app
    # command that runs the application in the docker container
    command: >
     sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword